### ISSUE TITLE
Firmware for custom board?

### ISSUE THREAD

**Issue by Salmon731** [o-devices/bldc-ffb-wheel#6]
Hey brother/sister, i cant seem to find the firmware for custom board. It was here before. Is the project dead?

**Comment by olukelo** [comment]
Custom board is 'on hold'. Because of global chip shortage it is extremely difficult to source components for building it. So I switched to ODrive as stable source of boards( ton of them awailable at aliexpress). But. All previous commits are there. So you can checkout the project and revert to previous commit for everything that was there before. There is a plan to port firmware for other boards as well.

**Comment by Salmon731** [comment]
Thank you for the reply. Can we temporarily run mmos on your custom board until you get back on the firmware development for it?

**Comment by olukelo** [comment]
I'm not an expert in MMOS, so I can't guarantee.
